[build.environment]
  NODE_VERSION = "14"
  PLAYWRIGHT_BROWSERS_PATH = "0"

[build]
  publish = "dist"
  command = "npx pnpm i --store=node_modules/.pnpm-store && npx pnpm run build"

[[redirects]]
  from = "/lesson-1/*"
  to = "/lesson-1/index.html"
  status = 200

[[redirects]]
  from = "/lesson-2/*"
  to = "/lesson-2/index.html"
  status = 200

[[redirects]]
  from = "/lesson-3/*"
  to = "/lesson-3/index.html"
  status = 200

[[redirects]]
  from = "/lesson-4/*"
  to = "/lesson-4/index.html"
  status = 200

[[redirects]]
  from = "/lesson-5/*"
  to = "/lesson-5/index.html"
  status = 200

[[redirects]]
  from = "/lesson-6/*"
  to = "/lesson-6/index.html"
  status = 200

[[redirects]]
  from = "/lesson-7/*"
  to = "/lesson-7/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index/index.html"
  status = 200

